### ISSUE TITLE
Habit Tracker

### ISSUE THREAD

**Issue by ConradSelig** [ConradSelig/MikeVCS#17]
Using the Tasker app on my phone, track my habits and create a visual report.

- [ ] Save incoming tasks and create a visual report
- [ ] Use the machine learning module to predict next-day events
- [ ] Analyze the habits and create alerts for deficiencies.
