### ISSUE TITLE
Add todo item

### ISSUE THREAD

**Issue by ConradSelig** [ConradSelig/MikeVCS#8]
The todo item should contain the following data:

- [ ] Name of the todo item
- [ ] todo item Priority
- [ ] todo item due date

The library used for todo items in the past was pytodoist.todoist.
